/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    NutAnimate: typeof import('@nutui/nutui-taro')['Animate']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutBarrage: typeof import('@nutui/nutui-taro')['Barrage']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCard: typeof import('@nutui/nutui-taro')['Card']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutEcard: typeof import('@nutui/nutui-taro')['Ecard']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
  }
}
